# Generated by Django 4.1.6 on 2023-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollers'), ('eur', 'Euro')], default='usd', max_length=3),
        ),
    ]
