
version: '3.8'

services:
    django:
        build: .
        command: "gunicorn -c gunicorn.py test_rishat.wsgi" 
        # command: sh -c "gunicorn --bind 0.0.0.0:8000 test_rishat.wsgi "python manage.py runserver localhost:8000
        volumes:
            - .:/app
            - ./static:/app/static
        expose:
            - 8000
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
    nginx:
        image: nginx:1.19.8-alpine
        depends_on:
            - django
        expose:
            - 8080
        ports:
            - "80:8080"
        volumes:
            - ./static:/app/static
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            # - ./nginx/ssl:/etc/nginx/ssl
        
volumes:
  pg_data:
  static:
