version: '3.8'

services:
    django:
        build: .
        command: sh -c "gunicorn --bind 0.0.0.0:8000 test_rishat.wsgi "python manage.py runserver localhost:8080
        volumes:
            - .:/app
            - ./static:/app/static
        expose:
            - 8000
        environment:
            - DEBUG=1
    nginx:
        image: nginx:1.19.8-alpine
        depends_on:
            - django
        ports:
            - "8088:80"
        volumes:
            - ./static:/var/www/html/static
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  pg_data:
  static:
